# Generated by Django 4.0.4 on 2022-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_faq_modified_at_personalfaq_email_personalfaq_header_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalfaq',
            old_name='header',
            new_name='head',
        ),
        migrations.AlterField(
            model_name='faq',
            name='modified_at',
            field=models.DateField(auto_now=True, verbose_name='수정일'),
        ),
    ]
