# Generated by Django 4.0.3 on 2022-04-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_remove_faq_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
