# Generated by Django 4.0.3 on 2022-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_faq_modified_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='글 분류', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalfaq',
            name='inquiries',
        ),
        migrations.AddField(
            model_name='faq',
            name='comment',
            field=models.TextField(default='', verbose_name='답변'),
        ),
        migrations.AddField(
            model_name='personalcomment',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='FaqComment',
        ),
        migrations.AddField(
            model_name='personalfaq',
            name='category',
            field=models.ManyToManyField(help_text='선택해주세요.', to='support.category'),
        ),
    ]
