# Generated by Django 4.0.4 on 2022-04-17 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0011_category_remove_personalfaq_inquiries_faq_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='modifier',
            field=models.ManyToManyField(blank=True, related_name='writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
