# Generated by Django 4.0.4 on 2022-04-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_faq_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomment',
            name='reference',
            field=models.ManyToManyField(blank=True, related_name='PersonalFaq.category+', to='support.personalfaq'),
        ),
    ]
