# Generated by Django 4.0.4 on 2022-04-17 15:41

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_personalcomment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='modifier',
        ),
        migrations.AddField(
            model_name='faq',
            name='modifier',
            field=models.TextField(default=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='personalcomment',
            name='reference',
            field=models.ManyToManyField(blank=True, related_name='PersonalFaq.head+', to='support.personalfaq'),
        ),
    ]
