# Generated by Django 4.0.4 on 2022-04-17 15:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_remove_faq_modifier_faq_modifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='modifier',
            field=models.TextField(auto_created=django.contrib.auth.models.User, default=django.contrib.auth.models.User),
        ),
    ]
