# Generated by Django 4.0.4 on 2022-04-17 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0015_alter_faq_modifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Faq.writer+', to=settings.AUTH_USER_MODEL),
        ),
    ]
