# Generated by Django 4.0.3 on 2022-04-17 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0019_alter_faq_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomment',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PersonalComment.writer+', to=settings.AUTH_USER_MODEL),
        ),
    ]
